### ISSUE TITLE
Module not found: Error: Can't resolve '../dist/drag-component.umd.js' in '/Volumes/my-code/drag-component/src'

### ISSUE THREAD

**Issue by bubbletg** [fuxichen/drag-component#1]
ERROR in ./src/main.js 3:0-62
Module not found: Error: Can't resolve '../dist/drag-component.umd.js' in '/Volumes/my-code/drag-component/src'
resolve '../dist/drag-component.umd.js' in '/Volumes/my-code/drag-component/src'
  using description file: /Volumes/my-code/drag-component/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Volumes/my-code/drag-component/package.json (relative path: ./dist/drag-component.umd.js)
      no extension

**Comment by fuxichen** [comment]
#[3e21718](https://github.com/fuxichen/drag-component/commit/3e21718ea83075b95bdbc2ce16c50498e6fea262)
已修复
